'use client';

import React from 'react';
import { Plus, RotateCcw } from 'lucide-react';
import { Product } from '../../../types';
import { BannerLandingBlock, BenefitsLandingBlock, ContactButtonLandingBlock, CtaLandingBlock, HeroLandingBlock, LandingBlock, SpacerLandingBlock } from '../../../types/landing';
import { createLandingEntityId } from '../../../lib/landing/landingDefaults';
import { AddButton, Field, ImageUrlField, inputClass, ItemActions, labelClass, moveItem } from './BlockEditorFields';

export interface BlockEditorProps { block: LandingBlock; onChange: (block: LandingBlock) => void; products?: Product[]; primaryProduct?: Product | null; }

export function CommonBlockEditor({ block, onChange }: BlockEditorProps) {
  const style = block.style || {};
  const updateStyle = (patch: Partial<NonNullable<LandingBlock['style']>>) => onChange({ ...block, style: { ...style, ...patch } } as LandingBlock);
  return <div className="space-y-4"><h4 className="border-b border-white/10 pb-2 text-xs font-black uppercase text-gold-light">Hiển thị chung</h4>{[['Ẩn block', block.hidden, (checked: boolean) => onChange({ ...block, hidden: checked } as LandingBlock)], ['Hiện trên desktop', block.desktopVisible !== false, (checked: boolean) => onChange({ ...block, desktopVisible: checked } as LandingBlock)], ['Hiện trên mobile', block.mobileVisible !== false, (checked: boolean) => onChange({ ...block, mobileVisible: checked } as LandingBlock)]].map(([label, checked, change]) => <label key={String(label)} className="flex items-center justify-between text-xs text-gray-300"><span>{String(label)}</span><input type="checkbox" checked={Boolean(checked)} onChange={(event) => (change as (value: boolean) => void)(event.target.checked)} className="h-4 w-4 accent-[#f5c45a]" /></label>)}<div className="grid grid-cols-2 gap-3"><Field label="Màu nền"><input type="color" value={style.backgroundColor || '#111111'} onChange={(event) => updateStyle({ backgroundColor: event.target.value })} className="h-10 w-full border border-white/10 bg-black p-1" /></Field><Field label="Màu chữ"><input type="color" value={style.textColor || '#ffffff'} onChange={(event) => updateStyle({ textColor: event.target.value })} className="h-10 w-full border border-white/10 bg-black p-1" /></Field></div><Field label="Căn nội dung"><select value={style.alignment || 'left'} onChange={(event) => updateStyle({ alignment: event.target.value as 'left' | 'center' | 'right' })} className={inputClass}><option value="left">Trái</option><option value="center">Giữa</option><option value="right">Phải</option></select></Field><div className="grid grid-cols-2 gap-3"><Field label="Padding trên"><input type="number" min="0" max="300" value={style.paddingTop ?? 48} onChange={(event) => updateStyle({ paddingTop: Number(event.target.value) })} className={inputClass} /></Field><Field label="Padding dưới"><input type="number" min="0" max="300" value={style.paddingBottom ?? 48} onChange={(event) => updateStyle({ paddingBottom: Number(event.target.value) })} className={inputClass} /></Field></div></div>;
}

export function HeroBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as HeroLandingBlock; const patch = (data: Partial<HeroLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><h4 className="text-xs font-black uppercase text-gold-light">Nội dung Hero</h4><Field label="Dòng nhấn"><input value={value.eyebrow || ''} onChange={(e) => patch({ eyebrow: e.target.value })} className={inputClass} /></Field><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><Field label="Mô tả"><textarea rows={3} value={value.description || ''} onChange={(e) => patch({ description: e.target.value })} className={`${inputClass} resize-none`} /></Field><ImageUrlField label="Ảnh sản phẩm override" value={value.image} onChange={(image) => patch({ image: image || undefined })} /><ImageUrlField label="Ảnh nền" value={value.backgroundImage} onChange={(backgroundImage) => patch({ backgroundImage: backgroundImage || undefined })} /><div className="grid grid-cols-2 gap-3"><Field label="Nhãn CTA"><input value={value.ctaLabel || ''} onChange={(e) => patch({ ctaLabel: e.target.value })} className={inputClass} /></Field><Field label="Đích CTA"><input value={value.ctaTarget || ''} onChange={(e) => patch({ ctaTarget: e.target.value })} className={inputClass} /></Field></div></div>; }

export function BannerBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as BannerLandingBlock; const patch = (data: Partial<BannerLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><h4 className="text-xs font-black uppercase text-gold-light">Nội dung Banner</h4><ImageUrlField label="Ảnh desktop" value={value.image} onChange={(image) => patch({ image })} /><ImageUrlField label="Ảnh mobile" value={value.mobileImage} onChange={(mobileImage) => patch({ mobileImage })} /><Field label="Alt ảnh"><input value={value.alt || ''} onChange={(e) => patch({ alt: e.target.value })} className={inputClass} /></Field><Field label="Liên kết"><input value={value.href || ''} onChange={(e) => patch({ href: e.target.value })} className={inputClass} /></Field></div>; }

export function BenefitsBlockEditor({ block, onChange }: BlockEditorProps) {
  const value = block as BenefitsLandingBlock; const patch = (data: Partial<BenefitsLandingBlock>) => onChange({ ...value, ...data });
  return <div className="space-y-4"><h4 className="text-xs font-black uppercase text-gold-light">Nội dung Benefits</h4><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><div className="space-y-2">{value.items.map((item, index) => <div key={item.id} className="space-y-2 border border-white/10 p-3"><div className="flex items-center justify-between"><span className="text-[9px] uppercase text-gray-600">Lợi ích {index + 1}</span><ItemActions index={index} count={value.items.length} onMove={(direction) => patch({ items: moveItem(value.items, index, direction) })} onDelete={() => patch({ items: value.items.filter((entry) => entry.id !== item.id) })} /></div><input value={item.title} onChange={(e) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, title: e.target.value } : entry) })} placeholder="Tiêu đề" className={inputClass} /><textarea rows={2} value={item.description || ''} onChange={(e) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, description: e.target.value } : entry) })} placeholder="Mô tả" className={inputClass} /><ImageUrlField label="Icon hoặc ảnh" value={item.image || item.icon} onChange={(image) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, image, icon: undefined } : entry) })} /></div>)}<AddButton label="Thêm lợi ích" onClick={() => patch({ items: [...value.items, { id: createLandingEntityId('benefit'), title: 'Lợi ích mới', description: '' }] })} /></div></div>;
}

export function CtaBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as CtaLandingBlock; const patch = (data: Partial<CtaLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><h4 className="text-xs font-black uppercase text-gold-light">Nội dung CTA</h4><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><Field label="Mô tả"><textarea rows={3} value={value.description || ''} onChange={(e) => patch({ description: e.target.value })} className={inputClass} /></Field><Field label="Nhãn nút"><input value={value.buttonLabel || ''} onChange={(e) => patch({ buttonLabel: e.target.value })} className={inputClass} /></Field><Field label="Đích nút"><input value={value.buttonTarget || ''} onChange={(e) => patch({ buttonTarget: e.target.value })} className={inputClass} /></Field><ImageUrlField label="Ảnh nền" value={value.backgroundImage} onChange={(backgroundImage) => patch({ backgroundImage })} /></div>; }

export function SpacerBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as SpacerLandingBlock; return <div className="space-y-4"><Field label="Desktop (px)"><input type="number" min="0" max="500" value={value.desktopHeight} onChange={(e) => onChange({ ...value, desktopHeight: Number(e.target.value) })} className={inputClass} /></Field><Field label="Mobile (px)"><input type="number" min="0" max="500" value={value.mobileHeight} onChange={(e) => onChange({ ...value, mobileHeight: Number(e.target.value) })} className={inputClass} /></Field></div>; }

export function ContactButtonBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as ContactButtonLandingBlock; const patch = (data: Partial<ContactButtonLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><Field label="Kênh"><select value={value.channel} onChange={(e) => patch({ channel: e.target.value as ContactButtonLandingBlock['channel'] })} className={inputClass}><option value="call">Gọi điện</option><option value="zalo">Zalo</option><option value="messenger">Messenger</option><option value="shopee">Shopee</option></select></Field><Field label="Nhãn nút"><input value={value.label || ''} onChange={(e) => patch({ label: e.target.value })} className={inputClass} /></Field><Field label="Liên kết / SĐT"><input value={value.href || ''} onChange={(e) => patch({ href: e.target.value })} className={inputClass} /></Field><label className="flex items-center justify-between text-xs text-gray-300"><span>Cố định trên mobile</span><input type="checkbox" checked={Boolean(value.fixedOnMobile)} onChange={(e) => patch({ fixedOnMobile: e.target.checked })} /></label></div>; }

export function DeferredBlockEditor({ block }: BlockEditorProps) { return <div className="border border-amber-500/20 bg-amber-500/5 p-4 text-xs text-amber-200">Editor {block.type} chưa được gắn.</div>; }
export function ResetOverridesButton({ onReset }: { onReset: () => void }) { return <button type="button" onClick={onReset} className="flex w-full items-center justify-center gap-2 border border-white/10 py-2.5 text-[10px] font-bold uppercase text-gray-400"><RotateCcw className="h-4 w-4" />Xóa override, dùng dữ liệu Product</button>; }
