'use client';
import React from 'react';
import { LandingDesignTokens, LandingPage } from '../../../types/landing';
import { DARK_LANDING_DESIGN, getLandingDesign, LIGHT_LANDING_DESIGN } from '../../../lib/landing/landingDesign';
import { Field, inputClass } from './BlockEditorFields';
import { BlockEditorProps, HeroBlockEditor } from './BlockEditors';
import { HeroLandingBlock } from '../../../types/landing';
export default function LandingDesignSettings({ page, onChange }: { page: LandingPage; onChange: (page: LandingPage) => void }) {
  const design = getLandingDesign(page); const patch = (value: Partial<LandingDesignTokens>) => onChange({ ...page, design: { ...design, ...value } });
  const colors: Array<[keyof LandingDesignTokens, string]> = [['primaryColor', 'Màu chính'], ['accentColor', 'Màu nhấn'], ['backgroundColor', 'Màu nền'], ['surfaceColor', 'Màu bề mặt'], ['textColor', 'Màu chữ'], ['mutedTextColor', 'Chữ phụ']];
  return <div className="space-y-4"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => onChange({ ...page, layout: { ...page.layout, theme: 'dark' }, design: { ...DARK_LANDING_DESIGN } })} className="border border-white/10 bg-black py-2 text-[9px] font-bold uppercase text-white">Preset tối</button><button type="button" onClick={() => onChange({ ...page, layout: { ...page.layout, theme: 'light' }, design: { ...LIGHT_LANDING_DESIGN } })} className="border border-white/10 bg-white py-2 text-[9px] font-bold uppercase text-black">Preset sáng</button></div><div className="grid grid-cols-2 gap-3">{colors.map(([key, label]) => <Field key={key} label={label}><input type="color" value={String(design[key])} onChange={(e) => patch({ [key]: e.target.value })} className="h-10 w-full border border-white/10 bg-black p-1" /></Field>)}</div><div className="grid grid-cols-2 gap-3"><Field label="Font tiêu đề"><select value={design.headingFont} onChange={(e) => patch({ headingFont: e.target.value as LandingDesignTokens['headingFont'] })} className={inputClass}><option value="display">Display</option><option value="sans">Sans</option><option value="serif">Serif</option></select></Field><Field label="Font nội dung"><select value={design.bodyFont} onChange={(e) => patch({ bodyFont: e.target.value as LandingDesignTokens['bodyFont'] })} className={inputClass}><option value="sans">Sans</option><option value="display">Display</option><option value="serif">Serif</option></select></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Bo góc (px)"><input type="number" min="0" max="48" value={design.radius} onChange={(e) => patch({ radius: Number(e.target.value) })} className={inputClass} /></Field><Field label="Shadow"><select value={design.shadow} onChange={(e) => patch({ shadow: e.target.value as LandingDesignTokens['shadow'] })} className={inputClass}><option value="none">Không</option><option value="soft">Nhẹ</option><option value="strong">Đậm</option></select></Field><Field label="Container (px)"><input type="number" min="720" max="1600" value={design.containerWidth} onChange={(e) => patch({ containerWidth: Number(e.target.value) })} className={inputClass} /></Field><Field label="Section spacing"><input type="number" min="16" max="160" value={design.sectionSpacing} onChange={(e) => patch({ sectionSpacing: Number(e.target.value) })} className={inputClass} /></Field></div><Field label="Kiểu nút"><select value={design.buttonStyle} onChange={(e) => patch({ buttonStyle: e.target.value as LandingDesignTokens['buttonStyle'] })} className={inputClass}><option value="solid">Nền đặc</option><option value="outline">Viền</option><option value="pill">Bo tròn</option></select></Field></div>;
}

export function HeroDesignEditor({ block, onChange, ...props }: BlockEditorProps) {
  const hero = block as HeroLandingBlock;
  return <div className="space-y-4"><Field label="Bố cục Hero"><select value={hero.layout || 'right-image'} onChange={(event) => onChange({ ...hero, layout: event.target.value as HeroLandingBlock['layout'] })} className={inputClass}><option value="left-image">Ảnh bên trái</option><option value="right-image">Ảnh bên phải</option><option value="center">Căn giữa</option><option value="overlay">Nội dung phủ ảnh</option><option value="full-width">Toàn chiều rộng</option></select></Field><HeroBlockEditor block={block} onChange={onChange} {...props} /></div>;
}
