'use client';

import React from 'react';
import { createLandingEntityId } from '../../../lib/landing/landingDefaults';
import { FaqLandingBlock, FeaturesLandingBlock, GalleryLandingBlock, ReviewsLandingBlock, SpecificationsLandingBlock, VideoLandingBlock, WarrantyLandingBlock } from '../../../types/landing';
import { BlockEditorProps } from './BlockEditors';
import { AddButton, Field, ImageUrlField, inputClass, ItemActions, moveItem } from './BlockEditorFields';

export function GalleryBlockEditor({ block, onChange, primaryProduct }: BlockEditorProps) {
  const value = block as GalleryLandingBlock; const patch = (data: Partial<GalleryLandingBlock>) => onChange({ ...value, ...data });
  const addProductImages = () => { const known = new Set(value.images.map((item) => item.url)); const urls = [primaryProduct?.image, ...(primaryProduct?.images || [])].filter((url): url is string => Boolean(url) && !known.has(url!)); patch({ images: [...value.images, ...urls.map((url) => ({ id: createLandingEntityId('image'), url, alt: primaryProduct?.name }))] }); };
  return <div className="space-y-4"><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><Field label="Kiểu hiển thị"><select value={value.layout || 'grid'} onChange={(e) => patch({ layout: e.target.value as 'grid' | 'slider' })} className={inputClass}><option value="grid">Lưới ảnh</option><option value="slider">Slider ngang</option></select></Field>{primaryProduct && <button type="button" onClick={addProductImages} className="w-full border border-gold-dark/30 py-2 text-[10px] font-bold uppercase text-gold-light">Thêm ảnh từ Product</button>}<div className="space-y-2">{value.images.map((item, index) => <div key={item.id} className="space-y-2 border border-white/10 p-3"><div className="flex justify-between"><span className="text-[9px] uppercase text-gray-500">Ảnh {index + 1}</span><ItemActions index={index} count={value.images.length} onMove={(d) => patch({ images: moveItem(value.images, index, d) })} onDelete={() => patch({ images: value.images.filter((entry) => entry.id !== item.id) })} /></div><ImageUrlField label="Ảnh custom" value={item.url} onChange={(url) => patch({ images: value.images.map((entry) => entry.id === item.id ? { ...entry, url } : entry) })} /><Field label="Alt text"><input value={item.alt || ''} onChange={(e) => patch({ images: value.images.map((entry) => entry.id === item.id ? { ...entry, alt: e.target.value } : entry) })} className={inputClass} /></Field></div>)}<AddButton label="Thêm ảnh custom" onClick={() => patch({ images: [...value.images, { id: createLandingEntityId('image'), url: '', alt: '' }] })} /></div></div>;
}

export function VideoBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as VideoLandingBlock; const patch = (data: Partial<VideoLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><Field label="YouTube / TikTok / Facebook / URL video trực tiếp"><input value={value.url || ''} onChange={(e) => patch({ url: e.target.value })} placeholder="https://..." className={inputClass} /></Field><ImageUrlField label="Thumbnail" value={value.poster} onChange={(poster) => patch({ poster })} /><label className="flex items-center justify-between text-xs text-gray-300"><span>Tự động phát (mặc định tắt)</span><input type="checkbox" checked={Boolean(value.autoplay)} onChange={(e) => patch({ autoplay: e.target.checked })} /></label><p className="text-[10px] leading-5 text-gray-600">YouTube dùng chế độ nhúng riêng. TikTok/Facebook hiển thị liên kết an toàn nếu không thể embed. URL Cloudinary MP4/WebM phát trực tiếp.</p></div>; }

export function FeaturesBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as FeaturesLandingBlock; const patch = (data: Partial<FeaturesLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field>{value.items.map((item, index) => <div key={item.id} className="space-y-2 border border-white/10 p-3"><div className="flex justify-between"><span className="text-[9px] uppercase text-gray-500">Tính năng {index + 1}</span><ItemActions index={index} count={value.items.length} onMove={(d) => patch({ items: moveItem(value.items, index, d) })} onDelete={() => patch({ items: value.items.filter((entry) => entry.id !== item.id) })} /></div><input value={item.title} onChange={(e) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, title: e.target.value } : entry) })} placeholder="Tiêu đề" className={inputClass} /><textarea value={item.description || ''} onChange={(e) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, description: e.target.value } : entry) })} placeholder="Mô tả" className={inputClass} /><ImageUrlField label="Icon hoặc ảnh" value={item.image} onChange={(image) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, image } : entry) })} /></div>)}<AddButton label="Thêm tính năng" onClick={() => patch({ items: [...value.items, { id: createLandingEntityId('feature'), title: 'Tính năng mới' }] })} /></div>; }

export function SpecificationsBlockEditor({ block, onChange, primaryProduct }: BlockEditorProps) { const value = block as SpecificationsLandingBlock; const patch = (data: Partial<SpecificationsLandingBlock>) => onChange({ ...value, ...data }); const keys = Object.keys(primaryProduct?.specs || {}); return <div className="space-y-4"><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><label className="flex items-center justify-between text-xs text-gray-300"><span>Tự động lấy từ Product</span><input type="checkbox" checked={value.useProductSpecs !== false} onChange={(e) => patch({ useProductSpecs: e.target.checked, productId: e.target.checked ? (value.productId || primaryProduct?.id) : value.productId })} /></label>{value.useProductSpecs !== false && keys.length > 0 && <div className="space-y-1 border border-white/10 p-3"><span className="text-[9px] uppercase text-gray-500">Chọn thông số Product (không chọn = tất cả)</span>{keys.map((key) => <label key={key} className="flex gap-2 text-xs text-gray-300"><input type="checkbox" checked={!value.includeKeys?.length || value.includeKeys.includes(key)} onChange={(e) => { const current = value.includeKeys?.length ? value.includeKeys : keys; patch({ includeKeys: e.target.checked ? [...new Set([...current, key])] : current.filter((item) => item !== key) }); }} />{key}: {primaryProduct?.specs[key]}</label>)}</div>}<p className="text-[10px] text-gray-600">Các dòng custom bên dưới là override/bổ sung, không sao chép toàn bộ Product.</p>{(value.customRows || []).map((row, index) => <div key={row.id} className="border border-white/10 p-3"><div className="mb-2 flex justify-end"><ItemActions index={index} count={(value.customRows || []).length} onMove={(d) => patch({ customRows: moveItem(value.customRows || [], index, d) })} onDelete={() => patch({ customRows: (value.customRows || []).filter((entry) => entry.id !== row.id) })} /></div><div className="grid grid-cols-2 gap-2"><input value={row.label} onChange={(e) => patch({ customRows: (value.customRows || []).map((entry) => entry.id === row.id ? { ...entry, label: e.target.value } : entry) })} placeholder="Tên thông số" className={inputClass} /><input value={row.value} onChange={(e) => patch({ customRows: (value.customRows || []).map((entry) => entry.id === row.id ? { ...entry, value: e.target.value } : entry) })} placeholder="Giá trị" className={inputClass} /></div></div>)}<AddButton label="Thêm dòng thông số" onClick={() => patch({ customRows: [...(value.customRows || []), { id: createLandingEntityId('spec'), label: '', value: '' }] })} /></div>; }

export function ReviewsBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as ReviewsLandingBlock; const patch = (data: Partial<ReviewsLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field>{value.items.map((item, index) => <div key={item.id} className="space-y-2 border border-white/10 p-3"><div className="flex justify-end"><ItemActions index={index} count={value.items.length} onMove={(d) => patch({ items: moveItem(value.items, index, d) })} onDelete={() => patch({ items: value.items.filter((entry) => entry.id !== item.id) })} /></div><input value={item.name} onChange={(e) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, name: e.target.value } : entry) })} placeholder="Tên khách" className={inputClass} /><textarea value={item.content} onChange={(e) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, content: e.target.value } : entry) })} placeholder="Nội dung" className={inputClass} /><Field label="Số sao"><select value={item.rating || 5} onChange={(e) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, rating: Number(e.target.value) } : entry) })} className={inputClass}>{[1,2,3,4,5].map((star) => <option key={star} value={star}>{star} sao</option>)}</select></Field><ImageUrlField label="Ảnh khách / sản phẩm" value={item.image} onChange={(image) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, image } : entry) })} /></div>)}<AddButton label="Thêm đánh giá" onClick={() => patch({ items: [...value.items, { id: createLandingEntityId('review'), name: '', content: '', rating: 5 }] })} /></div>; }

export function FaqBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as FaqLandingBlock; const patch = (data: Partial<FaqLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field>{value.items.map((item, index) => <div key={item.id} className="space-y-2 border border-white/10 p-3"><div className="flex justify-end"><ItemActions index={index} count={value.items.length} onMove={(d) => patch({ items: moveItem(value.items, index, d) })} onDelete={() => patch({ items: value.items.filter((entry) => entry.id !== item.id) })} /></div><input value={item.question} onChange={(e) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, question: e.target.value } : entry) })} placeholder="Câu hỏi" className={inputClass} /><textarea value={item.answer} onChange={(e) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, answer: e.target.value } : entry) })} placeholder="Câu trả lời" className={inputClass} /><label className="flex gap-2 text-xs text-gray-300"><input type="checkbox" checked={Boolean(item.openByDefault)} onChange={(e) => patch({ items: value.items.map((entry) => entry.id === item.id ? { ...entry, openByDefault: e.target.checked } : entry) })} />Mở mặc định</label></div>)}<AddButton label="Thêm câu hỏi" onClick={() => patch({ items: [...value.items, { id: createLandingEntityId('faq'), question: '', answer: '' }] })} /></div>; }

export function WarrantyBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as WarrantyLandingBlock; const patch = (data: Partial<WarrantyLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><Field label="Nội dung"><textarea rows={4} value={value.description || ''} onChange={(e) => patch({ description: e.target.value })} className={inputClass} /></Field><ImageUrlField label="Icon hoặc ảnh" value={value.image} onChange={(image) => patch({ image })} />{(value.items || []).map((item, index) => <div key={`${index}-${item}`} className="flex gap-2"><input value={item} onChange={(e) => patch({ items: (value.items || []).map((entry, i) => i === index ? e.target.value : entry) })} className={inputClass} /><ItemActions index={index} count={(value.items || []).length} onMove={(d) => patch({ items: moveItem(value.items || [], index, d) })} onDelete={() => patch({ items: (value.items || []).filter((_, i) => i !== index) })} /></div>)}<AddButton label="Thêm điểm bảo hành" onClick={() => patch({ items: [...(value.items || []), ''] })} /></div>; }
