'use client';

import React, { useState } from 'react';
import { createLandingEntityId } from '../../../lib/landing/landingDefaults';
import { ComboLandingBlock, CountdownLandingBlock, GiftLandingBlock, LandingProductReference, OrderFormLandingBlock, PriceLandingBlock } from '../../../types/landing';
import { BlockEditorProps, ResetOverridesButton } from './BlockEditors';
import { AddButton, Field, ImageUrlField, inputClass, ItemActions, moveItem, ProductPickerDialog } from './BlockEditorFields';

function ProductReferenceRows({ items, products, onChange }: { items: LandingProductReference[]; products: NonNullable<BlockEditorProps['products']>; onChange: (items: LandingProductReference[]) => void }) {
  const [picking, setPicking] = useState(false);
  return <div className="space-y-2">{items.map((item, index) => { const product = products.find((entry) => entry.id === item.productId); return <div key={`${item.productId}-${index}`} className="flex items-center gap-2 border border-white/10 p-2"><img src={item.overrides?.image || product?.image} alt="" className="h-12 w-12 bg-white object-contain" /><div className="min-w-0 flex-1"><b className="line-clamp-2 text-[10px] uppercase text-white">{item.overrides?.title || product?.name || item.productId}</b><input type="number" min="1" value={item.quantity || 1} onChange={(e) => onChange(items.map((entry, i) => i === index ? { ...entry, quantity: Math.max(1, Number(e.target.value)) } : entry))} className={`${inputClass} mt-1 py-1`} /></div><ItemActions index={index} count={items.length} onMove={(d) => onChange(moveItem(items, index, d))} onDelete={() => onChange(items.filter((_, i) => i !== index))} /></div>; })}<AddButton label="Chọn thêm Product" onClick={() => setPicking(true)} />{picking && <ProductPickerDialog products={products} title="Chọn Product" onClose={() => setPicking(false)} onSelect={(product) => { onChange([...items, { productId: product.id, quantity: 1 }]); setPicking(false); }} />}</div>;
}

export function PriceBlockEditor({ block, onChange, primaryProduct }: BlockEditorProps) { const value = block as PriceLandingBlock; const patch = (data: Partial<PriceLandingBlock>) => onChange({ ...value, ...data }); const usingProduct = value.useProductPrice !== false && value.displayPrice == null; return <div className="space-y-4"><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><label className="flex items-center justify-between text-xs text-gray-300"><span>Lấy giá từ Product</span><input type="checkbox" checked={usingProduct} onChange={(e) => patch(e.target.checked ? { useProductPrice: true, displayPrice: undefined, compareAtPrice: undefined, productId: value.productId || primaryProduct?.id } : { useProductPrice: false })} /></label><Field label="Giá hiển thị override"><input type="number" min="0" value={value.displayPrice ?? ''} onChange={(e) => patch({ displayPrice: e.target.value ? Number(e.target.value) : undefined, useProductPrice: !e.target.value })} className={inputClass} /></Field><Field label="Giá so sánh"><input type="number" min="0" value={value.compareAtPrice ?? ''} onChange={(e) => patch({ compareAtPrice: e.target.value ? Number(e.target.value) : undefined })} className={inputClass} /></Field><Field label="Nhãn giảm giá"><input value={value.badge || ''} onChange={(e) => patch({ badge: e.target.value })} className={inputClass} /></Field><Field label="Nội dung khuyến mãi"><textarea value={value.promotionText || ''} onChange={(e) => patch({ promotionText: e.target.value })} className={inputClass} /></Field><Field label="Nhãn CTA"><input value={value.ctaLabel || ''} onChange={(e) => patch({ ctaLabel: e.target.value })} className={inputClass} /></Field><ResetOverridesButton onReset={() => patch({ useProductPrice: true, displayPrice: undefined, compareAtPrice: undefined, productId: primaryProduct?.id })} /></div>; }

export function ComboBlockEditor({ block, onChange, products = [] }: BlockEditorProps) { const value = block as ComboLandingBlock; const patch = (data: Partial<ComboLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><Field label="Tiêu đề combo"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><h5 className="text-[10px] font-black uppercase text-gold-light">Sản phẩm trong combo</h5><ProductReferenceRows items={value.products} products={products} onChange={(items) => patch({ products: items })} /><Field label="Giá combo override"><input type="number" min="0" value={value.comboPrice ?? ''} onChange={(e) => patch({ comboPrice: e.target.value ? Number(e.target.value) : undefined })} className={inputClass} /></Field><Field label="Giá so sánh"><input type="number" min="0" value={value.compareAtPrice ?? ''} onChange={(e) => patch({ compareAtPrice: e.target.value ? Number(e.target.value) : undefined })} className={inputClass} /></Field><h5 className="text-[10px] font-black uppercase text-gold-light">Product quà tặng</h5><ProductReferenceRows items={value.gifts || []} products={products} onChange={(gifts) => patch({ gifts })} /><Field label="Nhãn CTA"><input value={value.ctaLabel || ''} onChange={(e) => patch({ ctaLabel: e.target.value })} className={inputClass} /></Field></div>; }

export function GiftBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as GiftLandingBlock; const patch = (data: Partial<GiftLandingBlock>) => onChange({ ...value, ...data }); const items = value.items || []; return <div className="space-y-4"><Field label="Tiêu đề khối"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><Field label="Mô tả chung"><textarea value={value.description || ''} onChange={(e) => patch({ description: e.target.value })} className={inputClass} /></Field>{items.map((item, index) => <div key={item.id} className="space-y-2 border border-white/10 p-3"><div className="flex justify-end"><ItemActions index={index} count={items.length} onMove={(d) => patch({ items: moveItem(items, index, d) })} onDelete={() => patch({ items: items.filter((entry) => entry.id !== item.id) })} /></div><input value={item.title} onChange={(e) => patch({ items: items.map((entry) => entry.id === item.id ? { ...entry, title: e.target.value } : entry) })} placeholder="Tên quà" className={inputClass} /><textarea value={item.description || ''} onChange={(e) => patch({ items: items.map((entry) => entry.id === item.id ? { ...entry, description: e.target.value } : entry) })} placeholder="Mô tả" className={inputClass} /><Field label="Giá trị tham khảo"><input type="number" min="0" value={item.estimatedValue ?? ''} onChange={(e) => patch({ items: items.map((entry) => entry.id === item.id ? { ...entry, estimatedValue: e.target.value ? Number(e.target.value) : undefined } : entry) })} className={inputClass} /></Field><ImageUrlField label="Ảnh quà" value={item.image} onChange={(image) => patch({ items: items.map((entry) => entry.id === item.id ? { ...entry, image } : entry) })} /></div>)}<AddButton label="Thêm quà tặng" onClick={() => patch({ items: [...items, { id: createLandingEntityId('gift'), title: 'Quà tặng mới' }] })} /></div>; }

export function CountdownBlockEditor({ block, onChange }: BlockEditorProps) { const value = block as CountdownLandingBlock; const patch = (data: Partial<CountdownLandingBlock>) => onChange({ ...value, ...data }); return <div className="space-y-4"><Field label="Tiêu đề"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><Field label="Ngày giờ kết thúc"><input type="datetime-local" value={value.endsAt?.slice(0, 16) || ''} onChange={(e) => patch({ endsAt: e.target.value || undefined })} className={inputClass} /></Field><Field label="Múi giờ"><select value={value.timezone || 'Asia/Ho_Chi_Minh'} onChange={(e) => patch({ timezone: e.target.value })} className={inputClass}><option value="Asia/Ho_Chi_Minh">Việt Nam (GMT+7)</option><option value="UTC">UTC</option></select></Field><Field label="Nội dung khi hết hạn"><textarea value={value.expiredMessage || ''} onChange={(e) => patch({ expiredMessage: e.target.value })} className={inputClass} /></Field><label className="flex items-center justify-between text-xs text-gray-300"><span>Ẩn block khi hết hạn</span><input type="checkbox" checked={Boolean(value.hideWhenExpired)} onChange={(e) => patch({ hideWhenExpired: e.target.checked })} /></label></div>; }

export function OrderFormBlockEditor({ block, onChange, primaryProduct }: BlockEditorProps) { const value = block as OrderFormLandingBlock; const patch = (data: Partial<OrderFormLandingBlock>) => onChange({ ...value, ...data }); const type = value.formType || 'order'; const fields: Array<[string, keyof OrderFormLandingBlock]> = [['Họ tên', 'showName'], ['Khu vực', 'showAddress'], ['Ghi chú', 'showNote'], ['Số lượng', 'showQuantity'], ['Tên cửa hàng / doanh nghiệp', 'showBusinessName'], ['Mô hình kinh doanh', 'showBusinessType'], ['Sản lượng dự kiến', 'showEstimatedVolume']]; return <div className="space-y-4"><Field label="Loại form"><select value={type} onChange={(e) => patch({ formType: e.target.value as OrderFormLandingBlock['formType'] })} className={inputClass}><option value="order">Đặt hàng</option><option value="consultation">Nhận tư vấn</option><option value="phone-only">Chỉ để lại số điện thoại</option></select></Field><Field label="Tiêu đề form"><input value={value.title || ''} onChange={(e) => patch({ title: e.target.value })} className={inputClass} /></Field><Field label="Mô tả"><textarea value={value.description || ''} onChange={(e) => patch({ description: e.target.value })} className={inputClass} /></Field><Field label="Nội dung nút gửi"><input value={value.submitLabel || ''} onChange={(e) => patch({ submitLabel: e.target.value })} className={inputClass} /></Field><Field label="Thông báo thành công"><textarea value={value.successMessage || ''} onChange={(e) => patch({ successMessage: e.target.value })} className={inputClass} /></Field><div className="space-y-2 border border-white/10 p-3"><p className="text-[9px] font-bold uppercase text-gray-500">Trường hiển thị</p>{type !== 'phone-only' && fields.map(([label, key]) => <label key={key} className="flex items-center justify-between text-xs text-gray-300"><span>{label}</span><input type="checkbox" checked={['showName', 'showAddress', 'showNote', 'showQuantity'].includes(key) ? value[key] !== false : Boolean(value[key])} onChange={(e) => patch({ [key]: e.target.checked } as Partial<OrderFormLandingBlock>)} /></label>)}<label className="flex items-center justify-between text-xs text-white"><b>Số điện thoại</b><span className="text-[9px] uppercase text-gold-light">Luôn bắt buộc</span></label></div>{primaryProduct && <button type="button" onClick={() => patch({ productIds: [primaryProduct.id] })} className="w-full border border-gold-dark/30 py-2 text-[10px] uppercase text-gold-light">Gắn Product chính vào form</button>}</div>; }
